//ex 1
function saluer(){
    console.log("bonjour, tout le monde")
}

saluer();
//ex 2
function saluerNom(nom){
    console.log("bonjour" +nom);
}
saluerNom(" ikram");
//ex 3
function addition(a,b){
    return a +b ;
}
console.log(addition(5,10));
//ex 4
function afficherMessage(message){
    console.log(message) ;
}
afficherMessage("salut le maroc");
//ex 5
function saluer(nom= " invité"){
    console.log("hello "+nom);
}
saluer();
saluer("hiba");
//Ex 6
function multiplication(a,b) {
    return a * b;
}
multiplication();
console.log(multiplication(10,20));
//ex 7
